# Enable mouse
set -g mouse on

# Change prefix key
unbind C-b
set -g prefix C-SPACE
bind C-s send-prefix

set -a terminal-features "tmux-256color:RGB"
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Easy navigate between nvim and tmux
# set -g @plugin 'christoomey/vim-tmux-navigator'

# Theme for tmux
# set -g @plugin 'catppuccin/tmux'
BLACK=#171717
WHITE=#CACACA
GRAY=#4E4E4E
BLUE=#87AFFF
GREEN=#AFD787
YELLOW=#D7D787
set -g status-left "[#S] "
set -g status-left-length 50
set-option -g status-style bg=${BLACK}
set-option -g window-status-format "\
#[bg=${WHITE}] #I \
#[bg=${GRAY}] #W #[default]"
set-option -g window-status-current-format "\
#[fg=${GRAY},bg=${GREEN}] #I \
#[fg=${GREEN},bg=${GRAY}] #W #[default]"

# Enable yank in tmux
set -g @plugin 'tmux-plugins/tmux-yank'

# Store tmux session
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

# set -g @plugin ''

# Set vi-mode
set-window-option -g mode-keys vi
# Keybindings
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open new pane in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind t display-popup -d "#{pane_current_path}" -w 80% -h 80%
bind c new-window -c "#{pane_current_path}"

# bind r source-file ~/.config/tmux/tmux.conf; display-message "Config Reloaded!"
bind r source-file ~/.config/tmux/tmux.conf
bind b attach-session -t backend
bind h attach-session -t home
bind f display-popup -w 80% -h 80% -B -E "$HOME/.local/libexec/dotfiles/tmux-sessionizer.sh"
bind g display-popup -w 80% -h 80% -E "lazygit"

# Auto restore
# set -g @continuum-restore 'on'

# Solve key conflicts
# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
unbind C-l
# bind l select-pane -R
# bind \ select-pane -l

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
