return {
	'nvim-treesitter/nvim-treesitter',
	build = ':TSUpdate',
	main = 'nvim-treesitter.configs',

	opts = {
		ensure_installed = {
			'bash',
			'c',
			'diff',
			'html',
			'lua',
			'luadoc',
			'markdown',
			'markdown_inline',
			'query',
			'vim',
			'vimdoc',
			'rust',
			'python',
		},
		auto_install = true,
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = {
				'bash',
				'c',
				'diff',
				'html',
				'lua',
				'luadoc',
				'markdown',
				'markdown_inline',
				'query',
				'vim',
				'vimdoc',
				'rust',
				'python',
			},
		},
		-- indent = { enable = true},
	},
}
